# Rose Pine Starship Config - Just enough, not too much
# version: 1.0.0
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
continuation_prompt = "... "
palette = 'rose-pine'

format = """$username\
$hostname\
$directory\
$git_branch\
$git_status\
$docker_context\
$kubernetes\
$aws\
$gcloud\
$azure\
$python\
$nodejs\
$rust\
$golang\
$java\
$terraform\
$character"""

right_format = """$cmd_duration\
$time"""

[palettes.rose-pine]
# Base Rose Pine colors
base = '#191724'
surface = '#1f1d2e'
overlay = '#26233a'
muted = '#6e6a86'
subtle = '#908caa'
text = '#e0def4'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'
highlight_low = '#21202e'
highlight_med = '#403d52'
highlight_high = '#524f67'

[character]
success_symbol = "[>](foam bold)"
error_symbol = "[x](love bold)"
vimcmd_symbol = "[:](@{iris})"

[username]
style_user = "bg:overlay fg:iris"
style_root = "bg:overlay fg:love"
format = "[](fg:overlay)[ 󰧱 $user ]($style)[](fg:overlay)@"
show_always = true

[hostname]
ssh_only = false
format = "[](fg:overlay)[ $hostname ]($style)[](fg:overlay) "
style = "bg:overlay fg:iris"

[directory]
truncation_length = 3
truncation_symbol = "…/"
read_only = " [RO]"
format = "[](fg:overlay)[ $path ]($style)[](fg:overlay)[$read_only](fg:love) "
style = "bg:overlay fg:pine"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[git_branch]
format = "[](fg:overlay)[ $symbol $branch ]($style)[](fg:overlay) "
style = "bg:overlay fg:foam"
symbol = ""
truncation_length = 20
truncation_symbol = "..."

[git_status]
disabled = false
style = "bg:overlay fg:love"
format = '[](fg:overlay)([$all_status$ahead_behind]($style))[](fg:overlay) '
up_to_date = '[ ✓ ](bg:overlay fg:iris)'
conflicted = '[!](bg:overlay fg:love)'
untracked = '[?\($count\)](bg:overlay fg:gold)'
stashed = '[\$](bg:overlay fg:iris)'
modified = '[*\($count\)](bg:overlay fg:gold)'
staged = '[+\($count\)](bg:overlay fg:gold)'
renamed = '[»\($count\)](bg:overlay fg:iris)'
deleted = '[x\($count\)](bg:overlay fg:love)'
ahead = '[⇡\(${count}\)](bg:overlay fg:foam)'
behind = '[⇣\(${count}\)](bg:overlay fg:rose)'
diverged = '⇕[\[](bg:overlay fg:iris)[⇡\(${ahead_count}\)](bg:overlay fg:foam)[⇣\(${behind_count}\)](bg:overlay fg:rose)[\]](bg:overlay fg:iris)'

[cmd_duration]
min_time = 2000
format = "[](fg:overlay)[ $duration ]($style)[](fg:overlay) "
style = "bg:overlay fg:text"

[time]
disabled = false
format = "[](fg:overlay)[ $time 󰴈 ]($style)[](fg:overlay)"
style = "bg:overlay fg:rose"
time_format = "%H:%M"

# Language indicators - minimal, no versions but with Rose Pine styling
[python]
format = "[](fg:overlay)[ py ]($style)[](fg:overlay) "
style = "bg:overlay fg:pine"

[nodejs]
format = "[](fg:overlay)[ js ]($style)[](fg:overlay) "
style = "bg:overlay fg:pine"
symbol = "󰎙 "

[rust]
format = "[](fg:overlay)[ rs ]($style)[](fg:overlay) "
style = "bg:overlay fg:pine"
symbol = " "

[golang]
format = "[](fg:overlay)[ go ]($style)[](fg:overlay) "
style = "bg:overlay fg:pine"
symbol = " "

[java]
format = "[](fg:overlay)[ java ]($style)[](fg:overlay) "
style = "bg:overlay fg:pine"
symbol = " "

[lua]
format = "[](fg:overlay)[ lua ]($style)[](fg:overlay) "
style = "bg:overlay fg:pine"

[ruby]
format = "[](fg:overlay)[ rb ]($style)[](fg:overlay) "
style = "bg:overlay fg:pine"

# Cloud and infrastructure
[terraform]
format = "[](fg:overlay)[ tf ]($style)[](fg:overlay) "
style = "bg:overlay fg:pine"

[docker_context]
format = "[](fg:overlay)[ docker ]($style)[](fg:overlay) "
style = "bg:overlay fg:pine"

[kubernetes]
format = "[](fg:overlay)[ k8s ]($style)[](fg:overlay) "
style = "bg:overlay fg:pine"

[aws]
format = "[](fg:overlay)[ aws ]($style)[](fg:overlay) "
style = "bg:overlay fg:foam"

[gcloud]
format = "[](fg:overlay)[ gcp ]($style)[](fg:overlay) "
style = "bg:overlay fg:pine"

[azure]
format = "[](fg:overlay)[ az ]($style)[](fg:overlay) "
style = "bg:overlay fg:pine"

# Disable everything else
[package]
disabled = true

[battery]
disabled = true

[sudo]
disabled = true

[jobs]
disabled = true

[memory_usage]
disabled = true

[localip]
disabled = true

[shlvl]
disabled = true

[shell]
disabled = true

[container]
disabled = true

[singularity]
disabled = true

[nix_shell]
disabled = true
